hash-format = "sha256"

[[files]]
file = "mods/appleskin.pw.toml"
hash = "c8a3a4e37febf2f355af3fade8c09212fd524cb7287744b4a428dcc9049b63b6"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "697873ffa46fdfc7b67e2a622c5ec719f3b25036bfbd82cc3937856011c257f4"
metafile = true

[[files]]
file = "mods/continuity.pw.toml"
hash = "cbd182feec72636573a2d0a2ba1a07bd108df55a1ea92de813a9b7675ca86542"
metafile = true

[[files]]
file = "mods/debugify.pw.toml"
hash = "5c948d5c926d5f4da14e033c96cbb301ac3d2c02ae4291ccd6a072194e1e9d28"
metafile = true

[[files]]
file = "mods/dynamic-fps.pw.toml"
hash = "5dd6666f515dd04d6425a20296c495f07d1f96c10365d956ab009bdbd0966a36"
metafile = true

[[files]]
file = "mods/dynamic-fullbright.pw.toml"
hash = "b1bd13479d82679bc801e20f281ef21a1f45d0b36289a7220153e1da3c1ef603"
metafile = true

[[files]]
file = "mods/ebe.pw.toml"
hash = "33323934d2437019bf96c3e4508739fe103c82c15f1259981795e124e6433019"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "d302620895cb7bbed2c35a6d4e9a7899e5fa927e7324a2a9367e014cf7248df4"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "9d89e86278be911668dd2215817a6e56b833c0453899c3c741ef7e91a58acad3"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "f7efd8724bd5aa92c99ddcf6f53e1371cbcda74bf291c557b411cb198823ebb9"
metafile = true

[[files]]
file = "mods/forge-config-api-port.pw.toml"
hash = "571ba77632efa87408447990598538c8801554114e961d7070080caf88b6cea3"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "07a4c33f7c68cc5b2f45bdbf3105f16b1ee973a6d3d4d4f63da2f04316b7cb3e"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "a74a9f9d1982965eb006994e5d50428851281e32f04a1276d2ec4c9e1e244e51"
metafile = true

[[files]]
file = "mods/lambdynamiclights.pw.toml"
hash = "9cdfe1aabacf0ecb757ed62251e16e97a1de6491cfcd3538b0c3a1c744cb826a"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "34e81f017bd87ca11ea53f4c03677b72d2db4c565b49e87581dfe908f549d73d"
metafile = true

[[files]]
file = "mods/malilib.pw.toml"
hash = "05b42c0f3103204e202c6b0e64a7d3f6d27393ed5f1bc061850890a2f8a9083d"
metafile = true

[[files]]
file = "mods/minihud.pw.toml"
hash = "4934054e1b2d95dc884eae9173932d0a9d8dc395c48bcba8da0b3c7765c4ba72"
metafile = true

[[files]]
file = "mods/modernfix.pw.toml"
hash = "753cc4d14e8ca72a0b9dc372ee93c4de9c2ee362978d992d5ab9bf9f01c3e02b"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "77004031cd79e1d63fdf27cfc7bc262701e0fe2257d0a2fca7d2161679a71a50"
metafile = true

[[files]]
file = "mods/obsidianui.pw.toml"
hash = "81cd39a74806173d7c11d5f62135d3991e5a61118954a085443083ba79dbfac1"
metafile = true

[[files]]
file = "mods/rrls.pw.toml"
hash = "6f933b5b0942dc7ef6a9c522415e1853318d45fe94eab56c15a0d024f104a5cb"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
hash = "81b1754cc253375f0ab17dac44fb9f8c884cbafaa9737fd8cdae2eff191f9a82"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "3a63c6af77f09489ea112ed9f95d9bf38abc01ef7f628a16d356857c87ada09e"
metafile = true

[[files]]
file = "mods/tweakeroo.pw.toml"
hash = "71b8abfa377547b60bf6c5f7edaeabd6e615f70bfd0c2484bdeb28362dbdcb90"
metafile = true

[[files]]
file = "mods/worldedit-cui.pw.toml"
hash = "08b0f7e09f08c0cb0d01e8174564c7219c8fc62edb73e1b1b3d3758efee004cf"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "ce3c8c8dd73fd279e68704fbac264549bac3e46960e4843ef10465c933b68a3d"
metafile = true
