hash-format = "sha256"

[[files]]
file = "mods/appleskin.pw.toml"
hash = "c8a3a4e37febf2f355af3fade8c09212fd524cb7287744b4a428dcc9049b63b6"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "697873ffa46fdfc7b67e2a622c5ec719f3b25036bfbd82cc3937856011c257f4"
metafile = true

[[files]]
file = "mods/continuity.pw.toml"
hash = "b6acdf8c5760b3e8f4c772d300f19ba45db349ab0a014e5652878cd87354837e"
metafile = true

[[files]]
file = "mods/debugify.pw.toml"
hash = "70120d013e17bec9b48c0f77528643fcd0887f623b9b2bf6568b355cc69f3627"
metafile = true

[[files]]
file = "mods/dynamic-fps.pw.toml"
hash = "5dd6666f515dd04d6425a20296c495f07d1f96c10365d956ab009bdbd0966a36"
metafile = true

[[files]]
file = "mods/dynamic-fullbright.pw.toml"
hash = "b1bd13479d82679bc801e20f281ef21a1f45d0b36289a7220153e1da3c1ef603"
metafile = true

[[files]]
file = "mods/ebe.pw.toml"
hash = "33323934d2437019bf96c3e4508739fe103c82c15f1259981795e124e6433019"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "d302620895cb7bbed2c35a6d4e9a7899e5fa927e7324a2a9367e014cf7248df4"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "55a5fbe541cb78318d4a2c177ad47e3fd65127d1d198fb9a8f4d49d18d9d7027"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "f7efd8724bd5aa92c99ddcf6f53e1371cbcda74bf291c557b411cb198823ebb9"
metafile = true

[[files]]
file = "mods/forge-config-api-port.pw.toml"
hash = "e7c1cce42df3843aea82c5cde390584b8aac4d7f499b73589938e0009ba9fc25"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "07a4c33f7c68cc5b2f45bdbf3105f16b1ee973a6d3d4d4f63da2f04316b7cb3e"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "a74a9f9d1982965eb006994e5d50428851281e32f04a1276d2ec4c9e1e244e51"
metafile = true

[[files]]
file = "mods/lambdynamiclights.pw.toml"
hash = "9cdfe1aabacf0ecb757ed62251e16e97a1de6491cfcd3538b0c3a1c744cb826a"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "fd0634bd62a8d0f17d049ea623c2cd536b77c075c992bbe9e8bd753553047192"
metafile = true

[[files]]
file = "mods/malilib.pw.toml"
hash = "47b55e9b13abe57557a456dd3ad61eef2a6fb4549b89482df86f2d3afd02d7db"
metafile = true

[[files]]
file = "mods/minihud.pw.toml"
hash = "e6337daca302333bd0e280b2702d70227678f68d3e5aeeb7fad745602038d462"
metafile = true

[[files]]
file = "mods/modernfix.pw.toml"
hash = "753cc4d14e8ca72a0b9dc372ee93c4de9c2ee362978d992d5ab9bf9f01c3e02b"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "77004031cd79e1d63fdf27cfc7bc262701e0fe2257d0a2fca7d2161679a71a50"
metafile = true

[[files]]
file = "mods/obsidianui.pw.toml"
hash = "81cd39a74806173d7c11d5f62135d3991e5a61118954a085443083ba79dbfac1"
metafile = true

[[files]]
file = "mods/rrls.pw.toml"
hash = "6f933b5b0942dc7ef6a9c522415e1853318d45fe94eab56c15a0d024f104a5cb"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
hash = "81b1754cc253375f0ab17dac44fb9f8c884cbafaa9737fd8cdae2eff191f9a82"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "49a945df6c416c4a1b326f39c97323041920b559619eb69bf19c2e8535711444"
metafile = true

[[files]]
file = "mods/tweakeroo.pw.toml"
hash = "a2ad72cb4be85ed8ec272a5cb49c31ac03a163f10682ccc43d1120c86da604c2"
metafile = true

[[files]]
file = "mods/worldedit-cui.pw.toml"
hash = "a0ab28136008c291b4dfa2d8bcc37a9fea254b79bdae35d0006a29065bb38864"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "ce3c8c8dd73fd279e68704fbac264549bac3e46960e4843ef10465c933b68a3d"
metafile = true
