name = "UnownPlain's Modpack"
author = "UnownPlain"
version = "1.21.10"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "68bc5a0604c45001a3a6012d549b629e7b015198b59f51b2f13dba620cb4ea5f"

[versions]
fabric = "0.17.2"
minecraft = "1.21.10"

[options]
acceptable-game-versions = ["1.21.10", "1.21.9"]
