name = "UnownPlain's Modpack"
author = "UnownPlain"
version = "1.20.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6bffb83c2e09d77056510249fb2246a5602612ab2af4e22401431f7d7d399d55"

[versions]
fabric = "0.18.1"
minecraft = "1.20.6"

[options]
acceptable-game-versions = ["1.20.6"]
