name = "UnownPlain's Modpack"
author = "UnownPlain"
version = "1.20.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9342acd35d0b6265c92896a0a028a301749a2598fe3a78b7336fb468178e8ae8"

[versions]
fabric = "0.18.1"
minecraft = "1.20.6"

[options]
acceptable-game-versions = ["1.20.6"]
