name = "UnownPlain's Modpack"
author = "UnownPlain"
version = "1.19.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "70aa6053ff047b59e20fd95a2ace603c89cbac26baac516fb1eafd2e49de0775"

[versions]
fabric = "0.18.1"
minecraft = "1.19.4"

[options]
acceptable-game-versions = ["1.19.4"]
