name = "UnownPlain's Modpack"
author = "UnownPlain"
version = "1.19.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "51bce1149462670fbc4f544c0161bd31bf63395c7b5ca2e76da7b74b84f43926"

[versions]
fabric = "0.18.1"
minecraft = "1.19.4"

[options]
acceptable-game-versions = ["1.19.4"]
