hash-format = "sha256"

[[files]]
file = "mods/appleskin.pw.toml"
hash = "4238ba514383c5035b45e5539224f4382f0957a345f0aeb5085f02fdc7feac3f"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "81992cfce98ecc582b108fdebaac5a5f64b0321f18c37b714eb7155df3cbd33d"
metafile = true

[[files]]
file = "mods/continuity.pw.toml"
hash = "f2c561ecc5161c36f5a8675b0391f5659bdd2684bdb091e91fd08c5f70df1136"
metafile = true

[[files]]
file = "mods/debugify.pw.toml"
hash = "ebc09edf8026fa3819985c9e7428ced1dab34caa4febcb79a334e2c07c826016"
metafile = true

[[files]]
file = "mods/dynamic-fps.pw.toml"
hash = "fbbb2fb64ef4cb44e825d114c9c975d6fd1e8952abd32731eec07d975838649a"
metafile = true

[[files]]
file = "mods/dynamic-fullbright.pw.toml"
hash = "c3aaeb7dae077e8fc5fa7c987f800c1498c0315224e0d8b052807cf581ec50bf"
metafile = true

[[files]]
file = "mods/ebe.pw.toml"
hash = "33323934d2437019bf96c3e4508739fe103c82c15f1259981795e124e6433019"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "b013ea45b312edf7707a4baf013590c2de8eb8e5ae8edf415416b3387b6ac500"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "c3059a1ee0cbb3e01d7648ce7783c0a98228b0705ceda04faa75fdc6da90f6d9"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "9aaf78da88ade519ad0f51c482b1142d6a6e0eccbe4de98385f3d1e35e9cb0b8"
metafile = true

[[files]]
file = "mods/forge-config-api-port.pw.toml"
hash = "4e69db58ce0e4c7f85f109c87f5396067fc5975c35c356e449edfb8ddaa53eed"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "2233bfc411a76fc29696cc549d9c51c908ac31fcb5e8446fea6bd5140d5b497c"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "3f68911b1dba6ba4bd23fd21d2f4511beb779aa19b18df041eec061711de0a97"
metafile = true

[[files]]
file = "mods/lambdynamiclights.pw.toml"
hash = "9c15d70a164a6e16b09212b6a24d097003f86bb595634a66c04b9a31dff38ff4"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "882c24d85417c48489e21307bdffdf34336839ff8ae69721b898a2910e8c0214"
metafile = true

[[files]]
file = "mods/malilib.pw.toml"
hash = "32ce8f5a092ebe11cd820035e86ae4560a012aa67da4fc736952651d007d50e4"
metafile = true

[[files]]
file = "mods/minihud.pw.toml"
hash = "1dba4ae04ccdc840e991c05fb64da12290d618e06fde9aa04ac212d1dce6eb1b"
metafile = true

[[files]]
file = "mods/modernfix.pw.toml"
hash = "753cc4d14e8ca72a0b9dc372ee93c4de9c2ee362978d992d5ab9bf9f01c3e02b"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "ce07fc310311d4db1c9b67c700d28b7cf80398b42eef19722fada7b435e49bb8"
metafile = true

[[files]]
file = "mods/obsidianui.pw.toml"
hash = "81cd39a74806173d7c11d5f62135d3991e5a61118954a085443083ba79dbfac1"
metafile = true

[[files]]
file = "mods/rrls.pw.toml"
hash = "be0dd3a2350704784a98646d662a6fe1b9541317f15b2bb221a720272e9792f0"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
hash = "59add93cfd8ecc09a3362fcac40cc1fb8c6f37fc0c736ff14b0a57b492474970"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "8a774daed87b7c1e3904f2915a241d53fb9f40992c0adba578ade41be236f2f6"
metafile = true

[[files]]
file = "mods/tweakeroo.pw.toml"
hash = "8642bf49d5c21ddfae43f3a3b393210581b659273e5c3b9f3f6a361f5ce72849"
metafile = true

[[files]]
file = "mods/worldedit-cui.pw.toml"
hash = "37f6988042edea1ceb67a4fedc68ea511301a9789176681d44d0d9a965ed68c4"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "90a3bb09a18d7b42704b6aa78a20d6a5721a69a13bcc2b70e3f02427433fd0b2"
metafile = true
