hash-format = "sha256"

[[files]]
file = "mods/appleskin.pw.toml"
hash = "23add7ca0daa9c1038fd73853e3c05dfaaf8494977c01ff3cb04aaf520bf5911"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "b220d7d18bfdd8ffd1403070806b8505644f836c731396fa8df61daaca4e5e61"
metafile = true

[[files]]
file = "mods/continuity.pw.toml"
hash = "cbd182feec72636573a2d0a2ba1a07bd108df55a1ea92de813a9b7675ca86542"
metafile = true

[[files]]
file = "mods/debugify.pw.toml"
hash = "9d0e6074e57e4c18c4595d209b25976b0ececf7a0dd5a18ce98b11b7232cf59f"
metafile = true

[[files]]
file = "mods/dynamic-fps.pw.toml"
hash = "0d2ba295afd308449f83a1301758f1940203a624107ff6a0112254b76d1b1cc3"
metafile = true

[[files]]
file = "mods/dynamic-fullbright.pw.toml"
hash = "b1bd13479d82679bc801e20f281ef21a1f45d0b36289a7220153e1da3c1ef603"
metafile = true

[[files]]
file = "mods/ebe.pw.toml"
hash = "33323934d2437019bf96c3e4508739fe103c82c15f1259981795e124e6433019"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "fcccc1c79bbbaad00e1657dca9a0c931c5753ddd5b5bd246a2009bc496f18b2c"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "aa42f14a74a68d10311edff10e3bbd717ffd15bfc238d7492e40c000be4195ac"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "180e2e0d290442ebf78d90bdebbb350218d0d28ee08d7c2a665354899ee1bf6f"
metafile = true

[[files]]
file = "mods/forge-config-api-port.pw.toml"
hash = "3cdceb4f360505f874eeaf791f5f42c0cff12504393495da5ef48d6fc0b5a1cb"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "799b155235113d4145a6ce6267240c632a2a83fd5f84113d023b07c9bac3cbed"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "a042ae14c9f48006d9560e24c55d4d744e922a7e8254365da7c5adb45ec6167d"
metafile = true

[[files]]
file = "mods/lambdynamiclights.pw.toml"
hash = "9c15d70a164a6e16b09212b6a24d097003f86bb595634a66c04b9a31dff38ff4"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "46efbb9055ae4037827d3f4126eb7c44e6f79ba7c13f50b61e6204b6bd3154bd"
metafile = true

[[files]]
file = "mods/malilib.pw.toml"
hash = "c2e6c8559b3209dd454af2816762957b8b6f82c0a945fb9fd874ed91ce60f968"
metafile = true

[[files]]
file = "mods/minihud.pw.toml"
hash = "cf0be70ef535974acd1a7b7fb1186f744df9fff48689c7af4de859459ac595c5"
metafile = true

[[files]]
file = "mods/modernfix.pw.toml"
hash = "753cc4d14e8ca72a0b9dc372ee93c4de9c2ee362978d992d5ab9bf9f01c3e02b"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "c658c1d8227bdf4cebfaf85c9edf413db9ff4c9e73de0e52cc657239361b9650"
metafile = true

[[files]]
file = "mods/obsidianui.pw.toml"
hash = "81cd39a74806173d7c11d5f62135d3991e5a61118954a085443083ba79dbfac1"
metafile = true

[[files]]
file = "mods/rrls.pw.toml"
hash = "9e0e8d6b99077cb89acf2210c5233d56e92af4f2f44090df52d1b00716340183"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
hash = "524dd93edc8b4c1c7e22191c6a2088cbc01899f97a0170423818da47627e648b"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "fc60e48fd86a17e3abb4f9ba0453707de7fd0353bad40bef804d734d2f370b38"
metafile = true

[[files]]
file = "mods/tweakeroo.pw.toml"
hash = "fe7ab8504ea132958899a00cc9ea262c6537a56fee5691ab7a1cba4d0b31bdf5"
metafile = true

[[files]]
file = "mods/worldedit-cui.pw.toml"
hash = "08b0f7e09f08c0cb0d01e8174564c7219c8fc62edb73e1b1b3d3758efee004cf"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "ff9775d72056b3327fb7e9c260e8275db9310a094f85c6b81399f7f5f7f0926c"
metafile = true
