hash-format = "sha256"

[[files]]
file = "mods/appleskin.pw.toml"
hash = "23add7ca0daa9c1038fd73853e3c05dfaaf8494977c01ff3cb04aaf520bf5911"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "81992cfce98ecc582b108fdebaac5a5f64b0321f18c37b714eb7155df3cbd33d"
metafile = true

[[files]]
file = "mods/continuity.pw.toml"
hash = "f2c561ecc5161c36f5a8675b0391f5659bdd2684bdb091e91fd08c5f70df1136"
metafile = true

[[files]]
file = "mods/debugify.pw.toml"
hash = "9d0e6074e57e4c18c4595d209b25976b0ececf7a0dd5a18ce98b11b7232cf59f"
metafile = true

[[files]]
file = "mods/dynamic-fps.pw.toml"
hash = "14858329dc0492480a15ace0fc73183749374f8ce32d2f219f6af9ab1006427a"
metafile = true

[[files]]
file = "mods/dynamic-fullbright.pw.toml"
hash = "c3aaeb7dae077e8fc5fa7c987f800c1498c0315224e0d8b052807cf581ec50bf"
metafile = true

[[files]]
file = "mods/ebe.pw.toml"
hash = "33323934d2437019bf96c3e4508739fe103c82c15f1259981795e124e6433019"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "fcccc1c79bbbaad00e1657dca9a0c931c5753ddd5b5bd246a2009bc496f18b2c"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "657b9997bce95fcf5a2f8832bfe75951660ef95ae73c90d18fb06d4025807141"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "180e2e0d290442ebf78d90bdebbb350218d0d28ee08d7c2a665354899ee1bf6f"
metafile = true

[[files]]
file = "mods/forge-config-api-port.pw.toml"
hash = "4e69db58ce0e4c7f85f109c87f5396067fc5975c35c356e449edfb8ddaa53eed"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "761daf9a06eaaadb68a2c13c112d9ba1c7761de907663f20ec778c44c48a758b"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "adcf4e8349912bf53a8e000914d70998cdf3d6c6176711ca63b2dde61d70f75d"
metafile = true

[[files]]
file = "mods/lambdynamiclights.pw.toml"
hash = "9c15d70a164a6e16b09212b6a24d097003f86bb595634a66c04b9a31dff38ff4"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "3a66971b0b892b085073accb5d7eff8bfcf9d4b26a9d5e011c8f9646502e97b8"
metafile = true

[[files]]
file = "mods/malilib.pw.toml"
hash = "cf468c9e1eeb13e14838bf79f5ecc9f62ac728cb2077326c5748caaa0b59fae9"
metafile = true

[[files]]
file = "mods/minihud.pw.toml"
hash = "5d627fa3928aef40e41c0930c3b59b4a9401ff53f57dc48c75fbebde9c4a4cce"
metafile = true

[[files]]
file = "mods/modernfix.pw.toml"
hash = "753cc4d14e8ca72a0b9dc372ee93c4de9c2ee362978d992d5ab9bf9f01c3e02b"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "fb43e903d1e92d4839f10585ccf3a7d19f6faf726bcbcf5107d9486dec4c0897"
metafile = true

[[files]]
file = "mods/obsidianui.pw.toml"
hash = "81cd39a74806173d7c11d5f62135d3991e5a61118954a085443083ba79dbfac1"
metafile = true

[[files]]
file = "mods/rrls.pw.toml"
hash = "4ff6f016541bb2f60df1df13505784545ad728c7b760509e34bdc65025b29ede"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
hash = "eb9d003efa03a0cb28cfffadd1c68cbab4681dd47c36b02d43ad1906ffd88d3e"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "34ecf58fc77d83aef3d6eaa8787a6e8d5288b2a0829da7cd93f8d2c0e7c9cdb1"
metafile = true

[[files]]
file = "mods/tweakeroo.pw.toml"
hash = "b321840dd0d3b60296d0a0f7d2a1ceb813c8152d88c955f9eaf7a3f40081c883"
metafile = true

[[files]]
file = "mods/worldedit-cui.pw.toml"
hash = "08b0f7e09f08c0cb0d01e8174564c7219c8fc62edb73e1b1b3d3758efee004cf"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "ff9775d72056b3327fb7e9c260e8275db9310a094f85c6b81399f7f5f7f0926c"
metafile = true
