name = "UnownPlain's Modpack"
author = "UnownPlain"
version = "1.21.11"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "26981877d95e6991db4e7b73a28d70484c02aad6fe696272f54719d230c393fe"

[versions]
fabric = "0.18.1"
minecraft = "1.21.11"

[options]
acceptable-game-versions = ["1.21.10", "1.21.11"]
