name = "UnownPlain's Modpack"
author = "UnownPlain"
version = "1.21.11"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "94fea155a91da5ae11978e7db11b65ce684b30d2e7dc5ae96de5c4ec3a31532d"

[versions]
fabric = "0.18.1"
minecraft = "1.21.11"

[options]
acceptable-game-versions = ["1.21.10", "1.21.11"]
