name = "UnownPlain's Modpack"
author = "UnownPlain"
version = "1.21.11"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "72692492a198b55bf6ab6139b381e0ba08e6863179631d001cb4b6ec378a25d2"

[versions]
fabric = "0.18.1"
minecraft = "1.21.11"

[options]
acceptable-game-versions = ["1.21.10", "1.21.11"]
